print('Hello world!')
print('Hi!!!')
print('Good afternoon!')
a=int(input('Введите число\n'))
b=int(input('Введите число\n'))
print(a-b)
print('C1')
print('C2')
print('C3')
print('C4')
print('5')
print('6')
print('7')
print('7')